{
	"openapi": "3.1.1",
	"info": {
		"title": "TWIN - Test Endpoints",
		"description": "REST API for TWIN - Test Endpoints.",
		"version": "1.0.0",
		"license": {
			"name": "Apache 2.0 License",
			"url": "https://opensource.org/licenses/Apache-2.0"
		}
	},
	"servers": [
		{
			"url": "https://localhost"
		}
	],
	"tags": [
		{
			"name": "Policy Administration Point",
			"description": "Endpoints for managing ODRL policies in the Policy Administration Point"
		},
		{
			"name": "Policy Enforcement Point",
			"description": "Endpoints for managing ODRL policies in the Policy Enforcement Point"
		},
		{
			"name": "Policy Negotiation Point",
			"description": "Endpoints for managing ODRL policies in the Policy Negotiation Point"
		},
		{
			"name": "Policy Negotiation Administration Point",
			"description": "Endpoints for managing ODRL policies in the Policy Negotiation Administration Point"
		}
	],
	"paths": {
		"/rights-management/pap": {
			"post": {
				"operationId": "papCreate",
				"summary": "Create a policy",
				"tags": [
					"Policy Administration Point"
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"requestBody": {
					"description": "The request structure for creating a policy.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PapCreateRequest"
							},
							"examples": {
								"papCreateRequestExample": {
									"value": {
										"@context": "https://www.w3.org/ns/odrl/2/",
										"@type": "Set",
										"permission": [
											{
												"target": "http://example.com/asset/1",
												"action": "use"
											}
										]
									}
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "The rest request ended in created response.",
						"headers": {
							"location": {
								"schema": {
									"type": "string"
								},
								"description": "e.g. urn:rights-management:abc123def456"
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pap/{id}": {
			"put": {
				"operationId": "papUpdate",
				"summary": "Update a policy",
				"tags": [
					"Policy Administration Point"
				],
				"parameters": [
					{
						"name": "id",
						"description": "The ID of the policy to update.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "urn:rights-management:abc123def456"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"requestBody": {
					"description": "The request structure for updating a policy.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlPolicy"
							},
							"examples": {
								"papUpdateRequestExample": {
									"value": {
										"@context": "https://www.w3.org/ns/odrl/2/",
										"@type": "Set",
										"uid": "urn:rights-management:abc123def456",
										"permission": [
											{
												"target": "http://example.com/asset/2",
												"action": "read"
											}
										]
									}
								}
							}
						}
					}
				},
				"responses": {
					"204": {
						"description": "The rest request ended in success with no data."
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			},
			"get": {
				"operationId": "papGet",
				"summary": "Get a policy",
				"tags": [
					"Policy Administration Point"
				],
				"parameters": [
					{
						"name": "id",
						"description": "The ID of the policy to get.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "urn:rights-management:abc123def456"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"200": {
						"description": "The response structure for getting a policy.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "https://schema.twindev.org/w3c-odrl/OdrlPolicy"
								},
								"examples": {
									"papGetResponseExample": {
										"value": {
											"@context": "https://www.w3.org/ns/odrl/2/",
											"@type": "Set",
											"uid": "urn:rights-management:abc123def456",
											"permission": [
												{
													"target": "http://example.com/asset/1",
													"action": "use"
												}
											]
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "papRemove",
				"summary": "Remove a policy",
				"tags": [
					"Policy Administration Point"
				],
				"parameters": [
					{
						"name": "id",
						"description": "The ID of the policy to remove.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "urn:rights-management:abc123def456"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"204": {
						"description": "The rest request ended in success with no data."
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pap/query": {
			"get": {
				"operationId": "papQuery",
				"summary": "Query policies",
				"tags": [
					"Policy Administration Point"
				],
				"parameters": [
					{
						"name": "conditions",
						"description": "The condition for the query.",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "pageSize",
						"description": "The number of entries to return per page.",
						"in": "query",
						"required": false,
						"schema": {
							"type": [
								"number",
								"string"
							]
						}
					},
					{
						"name": "cursor",
						"description": "The cursor to get next chunk of data, returned in previous response.",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string"
						},
						"example": "optional-pagination-cursor"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"200": {
						"description": "The response structure for querying policies.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PapQueryResponse"
								},
								"examples": {
									"papQueryResponseExample": {
										"value": {
											"cursor": "next-page-cursor",
											"policies": [
												{
													"@context": "https://www.w3.org/ns/odrl/2/",
													"@type": "Set",
													"uid": "urn:rights-management:abc123def456",
													"permission": [
														{
															"target": "http://example.com/asset/1",
															"action": "use"
														}
													]
												}
											]
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pep/intercept": {
			"post": {
				"operationId": "pepIntercept",
				"summary": "Intercept a request",
				"tags": [
					"Policy Enforcement Point"
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"requestBody": {
					"description": "The request structure for intercepting a request and enforcing a policy.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PepInterceptRequest"
							},
							"examples": {
								"pepInterceptRequestExample": {
									"value": {
										"assetType": "document",
										"action": "view",
										"data": {
											"id": "document-1",
											"param1": 1,
											"param2": 2
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "The response structure for intercepting a request and enforcing a policy.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PepInterceptResponse"
								},
								"examples": {
									"pepInterceptResponseExample": {
										"value": {
											"id": "document-1",
											"param1": 1
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pnp/negotiate": {
			"post": {
				"operationId": "pnpNegotiate",
				"summary": "Negotiate a policy",
				"tags": [
					"Policy Negotiation Point"
				],
				"requestBody": {
					"description": "The request structure for negotiating a policy.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PnpNegotiateRequest"
							},
							"examples": {
								"pnpNegotiateRequestExample": {
									"value": {
										"assetType": "document",
										"action": "view",
										"context": {
											"nodeIdentity": "urn:example:node:1"
										},
										"proof": {
											"created": "2024-08-22T11:56:56.272Z",
											"type": "DataIntegrityProof",
											"cryptosuite": "eddsa-jcs-2022",
											"proofPurpose": "assertionMethod",
											"proofValue": "z3Vcuh2BP9ShC4UEJ3yRZgcTJ6gmRtydDrh6AmY1zEciQqEWTvXfBZNxxjTzdJjT44cmn9VDWbBHqxFsX9fjsfXzK",
											"verificationMethod": "did:entity-storage:0x6363636363636363636363636363636363636363636363636363636363636363#assertion"
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "The response structure for negotiating a policy.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PolicyState"
								},
								"examples": {
									"IPnpNegotiateResponseExample": {
										"value": {
											"id": "policy-1",
											"status": "approved"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pnp/{policyId}": {
			"post": {
				"operationId": "pnpNegotiationState",
				"summary": "Get the state of a policy",
				"tags": [
					"Policy Negotiation Point"
				],
				"parameters": [
					{
						"name": "policyId",
						"description": "The ID of the policy being requested.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "policy-1"
					}
				],
				"requestBody": {
					"description": "The request structure for negotiating a policy.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PnpNegotiationStateRequest"
							},
							"examples": {
								"pnpNegotiationStateRequestExample": {
									"value": {
										"nodeIdentity": "urn:example:node:1",
										"proof": {
											"created": "2024-08-22T11:56:56.272Z",
											"type": "DataIntegrityProof",
											"cryptosuite": "eddsa-jcs-2022",
											"proofPurpose": "assertionMethod",
											"proofValue": "z3Vcuh2BP9ShC4UEJ3yRZgcTJ6gmRtydDrh6AmY1zEciQqEWTvXfBZNxxjTzdJjT44cmn9VDWbBHqxFsX9fjsfXzK",
											"verificationMethod": "did:entity-storage:0x6363636363636363636363636363636363636363636363636363636363636363#assertion"
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "The response structure for negotiation state request.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PolicyState"
								},
								"examples": {
									"IPnpNegotiationStateResponseExample": {
										"value": {
											"id": "policy-1",
											"status": "approved"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "pnpCancel",
				"summary": "Cancel a policy negotiation",
				"tags": [
					"Policy Negotiation Point"
				],
				"parameters": [
					{
						"name": "policyId",
						"description": "The ID of the policy being cancelled.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "policy-1"
					}
				],
				"requestBody": {
					"description": "The request structure for cancelling a policy negotiation.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PnpNegotiationCancelRequest"
							},
							"examples": {
								"pnpNegotiationCancelRequestExample": {
									"value": {
										"nodeIdentity": "urn:example:node:1",
										"proof": {
											"created": "2024-08-22T11:56:56.272Z",
											"type": "DataIntegrityProof",
											"cryptosuite": "eddsa-jcs-2022",
											"proofPurpose": "assertionMethod",
											"proofValue": "z3Vcuh2BP9ShC4UEJ3yRZgcTJ6gmRtydDrh6AmY1zEciQqEWTvXfBZNxxjTzdJjT44cmn9VDWbBHqxFsX9fjsfXzK",
											"verificationMethod": "did:entity-storage:0x6363636363636363636363636363636363636363636363636363636363636363#assertion"
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"204": {
						"description": "The rest request ended in success with no data."
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pnap/{policyId}": {
			"get": {
				"operationId": "pnapGet",
				"summary": "Get a policy negotiation",
				"tags": [
					"Policy Negotiation Administration Point"
				],
				"parameters": [
					{
						"name": "policyId",
						"description": "The ID of the policy being requested.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "policy-1"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"200": {
						"description": "The response structure for policy negotiation request.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PolicyNegotiation"
								},
								"examples": {
									"pnapGetResponseExample": {
										"value": {
											"id": "policy-1",
											"status": "manual",
											"dateCreated": "2025-09-03T00:00:00.000Z",
											"assetType": "document",
											"action": "view",
											"context": {}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			},
			"put": {
				"operationId": "pnapSet",
				"summary": "Set a policy negotiation",
				"tags": [
					"Policy Negotiation Administration Point"
				],
				"parameters": [
					{
						"name": "policyId",
						"description": "The ID of the policy being requested.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "policy-1"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"requestBody": {
					"description": "The request structure for setting a policy negotiation.",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/PolicyNegotiation"
							},
							"examples": {
								"pnapSetRequestExample": {
									"value": {
										"id": "policy-1",
										"status": "approved",
										"dateCreated": "2025-09-03T00:00:00.000Z",
										"assetType": "document",
										"action": "view",
										"context": {}
									}
								}
							}
						}
					}
				},
				"responses": {
					"204": {
						"description": "The rest request ended in success with no data."
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"operationId": "pnapRemove",
				"summary": "Remove a policy negotiation",
				"tags": [
					"Policy Negotiation Administration Point"
				],
				"parameters": [
					{
						"name": "policyId",
						"description": "The ID of the policy being removed.",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"style": "simple",
						"example": "policy-1"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"204": {
						"description": "The rest request ended in success with no data."
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		},
		"/rights-management/pnap": {
			"get": {
				"operationId": "pnapQuery",
				"summary": "Query policy negotiations",
				"tags": [
					"Policy Negotiation Administration Point"
				],
				"parameters": [
					{
						"name": "status",
						"description": "The status of the policy negotiations.",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string"
						},
						"example": "manual"
					},
					{
						"name": "cursor",
						"description": "The cursor for pagination.",
						"in": "query",
						"required": false,
						"schema": {
							"type": "string"
						},
						"example": "next-cursor"
					}
				],
				"security": [
					{
						"jwtBearerAuthScheme": []
					}
				],
				"responses": {
					"200": {
						"description": "The response structure for querying manual policy negotiations.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/PnapQueryResponse"
								},
								"examples": {
									"pnapQueryResponseExample": {
										"value": {
											"items": [
												{
													"id": "policy-1",
													"status": "manual",
													"dateCreated": "2025-09-03T00:00:00.000Z",
													"assetType": "document",
													"action": "view",
													"context": {}
												}
											],
											"cursor": "next-cursor"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "The server cannot process the request, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "GeneralError",
											"message": "component.error",
											"properties": {
												"foo": "bar"
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "You are not authorized to use the API or no credentials were supplied, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "UnauthorizedError",
											"message": "component.error"
										}
									}
								}
							}
						}
					},
					"500": {
						"description": "The server has encountered a situation it does not know how to handle, see the content for more details.",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/Error"
								},
								"examples": {
									"exampleResponse": {
										"value": {
											"name": "InternalServerError",
											"message": "component.error"
										}
									}
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"DidCryptoSuites": {
				"anyOf": [
					{
						"type": "string",
						"const": "eddsa-jcs-2022",
						"description": "The type for EdDSA crypto suite for JSON Canonicalization Scheme [RFC8785]. https://www.w3.org/TR/vc-di-eddsa/#eddsa-jcs-2022"
					},
					{
						"type": "string",
						"const": "eddsa-rdfc-2022",
						"description": "The type for EdDSA crypto suite for RDF Dataset Canonicalization. https://www.w3.org/TR/vc-di-eddsa/#eddsa-rdfc-2022"
					}
				],
				"description": "The types for DID Proof crypto suites."
			},
			"Error": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"description": "The name for the error."
					},
					"message": {
						"type": "string",
						"description": "The message for the error."
					},
					"source": {
						"type": "string",
						"description": "The source of the error."
					},
					"properties": {
						"type": "object",
						"additionalProperties": {},
						"description": "Any additional information for the error."
					},
					"stack": {
						"type": "string",
						"description": "The stack trace for the error."
					},
					"cause": {
						"$ref": "#/components/schemas/Error"
					}
				},
				"required": [
					"name",
					"message"
				],
				"additionalProperties": false,
				"description": "Model to describe serialized error."
			},
			"JsonWebSignature2020Proof": {
				"type": "object",
				"properties": {
					"@context": {
						"anyOf": [
							{
								"type": "string",
								"const": "https://w3id.org/security/suites/jws-2020/v1"
							},
							{
								"type": "array",
								"minItems": 1,
								"items": {
									"$ref": "https://schema.twindev.org/json-ld/JsonLdContextDefinitionElement"
								},
								"prefixItems": [
									{
										"type": "string",
										"const": "https://w3id.org/security/suites/jws-2020/v1"
									}
								]
							}
						],
						"description": "JSON-LD Context."
					},
					"type": {
						"type": "string",
						"const": "JsonWebSignature2020",
						"description": "JSON-LD Type."
					},
					"proofPurpose": {
						"type": "string",
						"description": "The reason the proof was created."
					},
					"verificationMethod": {
						"type": "string",
						"description": "The verification method of the proof."
					},
					"created": {
						"type": "string",
						"description": "The iso date of when the proof was created."
					},
					"jws": {
						"type": "string",
						"description": "The JSON Web Signature."
					}
				},
				"required": [
					"type",
					"proofPurpose"
				],
				"additionalProperties": false,
				"description": "Interface describing a did proof in JSON Web Signature 2020 Format. https://www.w3.org/TR/vc-jws-2020/"
			},
			"PapCreateRequest": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"uid": {
						"type": "string"
					},
					"@context": {
						"$ref": "https://schema.twindev.org/w3c-odrl/OdrlContextType"
					},
					"@type": {
						"$ref": "https://schema.twindev.org/w3c-odrl/PolicyType"
					},
					"profile": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"type": "string"
									}
								]
							}
						],
						"description": "The profile(s) this policy conforms to. IRIs identifying the ODRL Profile(s)."
					},
					"assigner": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlParty"
							}
						],
						"description": "The assigner of the policy. Applies to all rules unless overridden at rule level."
					},
					"assignee": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlParty"
							}
						],
						"description": "The assignee of the policy. Applies to all rules unless overridden at rule level."
					},
					"target": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlAsset"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"anyOf": [
											{
												"type": "string"
											},
											{
												"$ref": "https://schema.twindev.org/w3c-odrl/OdrlAsset"
											}
										]
									}
								]
							}
						],
						"description": "The target asset for the rule."
					},
					"action": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/ActionType"
							},
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlAction"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"anyOf": [
											{
												"$ref": "https://schema.twindev.org/w3c-odrl/ActionType"
											},
											{
												"$ref": "https://schema.twindev.org/w3c-odrl/OdrlAction"
											}
										]
									}
								]
							}
						],
						"description": "The action associated with the rule."
					},
					"inheritFrom": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"type": "string"
									}
								]
							}
						],
						"description": "The parent policy(ies) this policy inherits from. IRIs identifying the parent Policy(ies)."
					},
					"conflict": {
						"$ref": "https://schema.twindev.org/w3c-odrl/ConflictStrategyType"
					},
					"permission": {
						"type": "array",
						"items": false,
						"description": "The permissions in the policy. At least one of permission, prohibition, or obligation must be present.",
						"prefixItems": [
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlPermission"
							}
						]
					},
					"prohibition": {
						"type": "array",
						"items": false,
						"description": "The prohibitions in the policy. At least one of permission, prohibition, or obligation must be present.",
						"prefixItems": [
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlProhibition"
							}
						]
					},
					"obligation": {
						"type": "array",
						"items": false,
						"description": "The obligations in the policy. At least one of permission, prohibition, or obligation must be present.",
						"prefixItems": [
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlDuty"
							}
						]
					},
					"@id": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					},
					"@included": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					},
					"@graph": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					},
					"@nest": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					},
					"@reverse": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					},
					"@index": {
						"anyOf": [
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
							},
							{
								"type": "array",
								"items": false,
								"prefixItems": [
									{
										"$ref": "https://schema.twindev.org/json-ld/JsonLdNodePrimitive"
									}
								]
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdLanguageMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIndexMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIncludedBlock"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdIdMap"
							},
							{
								"$ref": "https://schema.twindev.org/json-ld/JsonLdTypeMap"
							}
						]
					}
				},
				"required": [
					"@context",
					"@graph",
					"@id",
					"@included",
					"@index",
					"@nest",
					"@reverse",
					"@type"
				],
				"description": "The body of the request - the policy to create (uid will be auto-generated)."
			},
			"PapQueryResponse": {
				"type": "object",
				"properties": {
					"cursor": {
						"type": "string",
						"description": "The cursor for the next page of results, if there are more results available."
					},
					"policies": {
						"type": "array",
						"items": false,
						"description": "The policies matching the query.",
						"prefixItems": [
							{
								"$ref": "https://schema.twindev.org/w3c-odrl/OdrlPolicy"
							}
						]
					}
				},
				"required": [
					"policies"
				],
				"additionalProperties": false,
				"description": "The body of the response."
			},
			"PepInterceptRequest": {
				"type": "object",
				"properties": {
					"assetType": {
						"type": "string",
						"description": "The type of the asset to enforce the policy on."
					},
					"action": {
						"type": "string",
						"description": "The action to perform on the asset."
					},
					"context": {
						"description": "The context in which the action is being performed. userIdentity and nodeIdentity should not be passed as they will be populated by the authenticated context on the server side."
					},
					"data": {
						"description": "The data to include in the request."
					}
				},
				"required": [
					"assetType",
					"action"
				],
				"additionalProperties": false,
				"description": "The body parameters of the request."
			},
			"PepInterceptResponse": {
				"description": "The manipulated data with any policies applied."
			},
			"PnapQueryResponse": {
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": false,
						"description": "The list of policy negotiations.",
						"prefixItems": [
							{
								"$ref": "#/components/schemas/PolicyNegotiation"
							}
						]
					},
					"cursor": {
						"type": "string",
						"description": "The cursor for pagination."
					}
				},
				"required": [
					"items"
				],
				"additionalProperties": false,
				"description": "The body of the response."
			},
			"PnpNegotiateRequest": {
				"type": "object",
				"properties": {
					"assetType": {
						"type": "string",
						"description": "The type of the asset being requested."
					},
					"action": {
						"type": "string",
						"description": "The action being performed on the asset."
					},
					"resourceId": {
						"type": "string",
						"description": "The id of the item being requested."
					},
					"context": {
						"$ref": "#/components/schemas/PolicyContext"
					},
					"requesterInformation": {
						"type": "object",
						"additionalProperties": {
							"type": "array",
							"items": false,
							"prefixItems": [
								{
									"$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
								}
							]
						},
						"description": "Additional information provided by the requester to determine if a policy can be created."
					},
					"proof": {
						"$ref": "https://schema.twindev.org/w3c-did/Proof"
					}
				},
				"required": [
					"assetType",
					"action",
					"context",
					"proof"
				],
				"additionalProperties": false,
				"description": "The body parameters of the request."
			},
			"PnpNegotiationCancelRequest": {
				"type": "object",
				"properties": {
					"nodeIdentity": {
						"type": "string",
						"description": "The node sending the request."
					},
					"proof": {
						"$ref": "https://schema.twindev.org/w3c-did/Proof"
					}
				},
				"required": [
					"nodeIdentity",
					"proof"
				],
				"additionalProperties": false,
				"description": "The body of the request."
			},
			"PnpNegotiationStateRequest": {
				"type": "object",
				"properties": {
					"nodeIdentity": {
						"type": "string",
						"description": "The node sending the request."
					},
					"proof": {
						"$ref": "https://schema.twindev.org/w3c-did/Proof"
					}
				},
				"required": [
					"nodeIdentity",
					"proof"
				],
				"additionalProperties": false,
				"description": "The body of the request."
			},
			"PolicyContext": {
				"type": "object",
				"properties": {
					"userIdentity": {
						"type": "string",
						"description": "The user identity to use in the decision making."
					},
					"nodeIdentity": {
						"type": "string",
						"description": "The node identity to use in the decision making."
					}
				},
				"additionalProperties": false,
				"description": "Context information to be used when making a policy decision."
			},
			"PolicyNegotiation": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"description": "The unique identifier for the policy."
					},
					"dateCreated": {
						"type": "string",
						"description": "The date and time when the negotiation was created."
					},
					"assetType": {
						"type": "string",
						"description": "The asset type the negotiation is for."
					},
					"action": {
						"type": "string",
						"description": "The action the negotiation is for."
					},
					"resourceId": {
						"type": "string",
						"description": "The resource id the negotiation is for."
					},
					"context": {
						"$ref": "#/components/schemas/PolicyContext"
					},
					"requesterInformation": {
						"type": "object",
						"additionalProperties": {
							"type": "array",
							"items": false,
							"prefixItems": [
								{
									"$ref": "https://schema.twindev.org/json-ld/JsonLdNodeObject"
								}
							]
						},
						"description": "The requester information."
					},
					"status": {
						"$ref": "#/components/schemas/PolicyNegotiationStatus"
					},
					"reason": {
						"type": "string",
						"description": "A reason which might be provided if the negotiation status is not approved."
					},
					"expires": {
						"type": "number",
						"description": "The expiration time for the policy negotiation."
					}
				},
				"required": [
					"id",
					"dateCreated",
					"assetType",
					"action",
					"context",
					"status"
				],
				"additionalProperties": false,
				"description": "Interface describing a rights management policy negotiation."
			},
			"PolicyNegotiationStatus": {
				"anyOf": [
					{
						"type": "string",
						"const": "manual",
						"description": "Manual - manual approval is required."
					},
					{
						"type": "string",
						"const": "approved",
						"description": "Approved - the negotiation has been approved."
					},
					{
						"type": "string",
						"const": "rejected",
						"description": "Rejected - the negotiation has been rejected."
					}
				],
				"description": "The status of the negotiation in the Policy Negotiation Point (PNP)."
			},
			"PolicyState": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"description": "The id of the policy."
					},
					"status": {
						"$ref": "#/components/schemas/PolicyNegotiationStatus"
					},
					"reason": {
						"type": "string",
						"description": "A reason which might be provided if the negotiation status is not approved."
					},
					"expires": {
						"type": "string",
						"description": "The expiration date of the policy created by the negotiation if it was approved, and it has an expiration date."
					}
				},
				"required": [
					"id",
					"status"
				],
				"additionalProperties": false,
				"description": "The state of the policy negotiation."
			}
		},
		"securitySchemes": {
			"jwtBearerAuthScheme": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	}
}
